=pod


=head1 NAME

Foorum::Manual::TroubleShooting - Foorum trouble fixes

=head1 Trouble Shooting

=head2 C<--Couldn't render template "plugin error - Math: plugin not found"--> (fixed with 2.20)

Template::Plugin::Math is removed from Template 2.19 but in 2.18

> cpan Template::Plugin::Math

install Template 2.18 first to install Plugin::Math

> cpan Template

then upgrade to 2.19

=head1 SEE ALSO

L<Foorum::Manual::README>, L<Foorum::Manual::INSTALL>, L<Foorum::Manual::Configure>

=cut
